services:
  - type: web
    name: rewardspin
    env: node
    region: ohio
    plan: free
    buildCommand: npm install --no-audit --no-fund && cd client && npm install --no-audit --no-fund && npm run build
    startCommand: node server/index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: ADMIN_TELEGRAM_IDS
        sync: false
      - key: ADS_PROVIDER
        value: adsgram
      - key: ADS_API_KEY
        sync: false
      - key: CLIENT_URL
        value: https://rewardspin.onrender.com
      - key: NODE_OPTIONS
        value: --max-old-space-size=512
      - key: GENERATE_SOURCEMAP
        value: false
